### PR TITLE
Update cats and monocle version

### PR DESCRIPTION
**Pull request by Jacoby6000**
This probably shouldn't be merged until the official cats 1.0 release, but I'm going to let it sit here so it doesn't get forgotten.

The biggest deal here is removing the need for Indexable, and the removal of scalaz as a dependency.

### CODE REVIEW

**Comment by AlexaDeWit** [comment]
I'd love to see a 1.0 bump here when the cats release is official  (Rob says probably before Christmas!).

I am looking at this library but I am using 1.0-RC1 of cats and thus effectively can't. Share the love please 👯

**Comment by Jacoby6000** [comment]
Cats 1.0 release is out. Now just need to wait for monocle to finish their milestone releases.

**Comment by Jacoby6000** [comment]
Monocle release should be soon. julien-truffaut/Monocle#550

**Comment by Jacoby6000** [comment]
After CI passes this should be good for release.  

I'm not sure what the release strategy should be for this.

**Comment by Jacoby6000** [comment]
@davegurnell How should we go about getting this out in to the wild? Increase minor release or what?

**Comment by davegurnell** [comment]
Yeah. Minor release, I reckon. I'll start on it now.

**Comment by davegurnell** [comment]
I just published this as version 0.5.0. `libraryDependencies` settings are in the README on develop.

**Pull request merged**
