### PR TITLE
Add law tests and profunctor instance for Rule.

### PR DESCRIPTION
**Pull request by Jacoby6000**
Additionally, made Eq and Order instances for Message and Path.  Those will need law tests as well, but cats 0.9.0 doesn't have laws for those.

### CODE REVIEW

**Comment by Jacoby6000** [comment]
Codecov is mad because I added some typeclass instances, but have no tests for them.  Their lawfulness is verified over in #12.

**Review by davegurnell — APPROVED** [review]
LGTM! 👍

**Comment by davegurnell** [comment]
I'm not too fussed about Codecov. It's a useful tool for providing an overview of what's happening but it's not the end of the world if the coverage goes down IMO.

**Comment by davegurnell** [comment]
I'm trying to put out a snapshot release but I'm getting GPG errors. Sigh.
I'll have to debug them later.

**Pull request merged**
