### PR TITLE
add build.properties file

### PR DESCRIPTION
**Pull request by aoiroaoino**
I think that it is better to lock the version of sbt.

### CODE REVIEW

**Comment by dispalt** [comment]
this isn't necessary anymore @aoiroaoino

**Comment by davegurnell** [comment]
Is it not? I'm happy to merge this, by the way, I've just been crap at responding to PRs on this library (sorry).

**Comment by dispalt** [comment]
Oh I just saw you had a https://github.com/davegurnell/checklist/blob/develop/project/build.properties

**Comment by davegurnell** [comment]
Aaaaah I see. Ok I'll close this when I'm next by a computer. Thanks for
the PR and sorry for the confusion!

**Comment by aoiroaoino** [comment]
I see. no problem :)

**Pull request closed without merging**
