### PR TITLE
Add some scaladoc for the refinement package, along with a couple of convenience methods.

### PR DESCRIPTION
**Pull request by Jacoby6000**

### CODE REVIEW

**Comment by Jacoby6000** [comment]
Hey @davegurnell, any way this can get merged in soon?

**Comment by davegurnell** [comment]
Merged! Sorry for the delay.

**Comment by davegurnell** [comment]
Released as `0.4.0`.

**Comment by davegurnell** [comment]
@Jacoby6000 I've also sent you a collaborator invite. It won't help with publishing to Sonatype but it will hopefully mitigate some of the long delays caused by me not being on top of things.

**Comment by Jacoby6000** [comment]
Cool deal! I'll hopefully not muddy things up too much 😉

**Pull request merged**
